### ISSUE TITLE
Remove JavaScript 101 section 

### ISSUE THREAD

**Issue by kevee** [jquery/learn.jquery.com#117]
The JavaScript 101 section, while containing useful content, seems to already duplicate resources available elsewhere - like the excellent [Mozilla Developer Network JavaScript Guide(https://developer.mozilla.org/en/JavaScript/Guide), among others.

If we remove it from the learn site, however, then we should probably include a preamble to the site about the assumptions the site makes about the users' experience, something like:
- General understanding of the web
- Basic grasp of HTML
- Introductory knowledge of JS (basically the current 101 pages).

**Comment by anthonybrown** [comment]
Looks like the JavaScript 101 has been removed?
