### ISSUE TITLE
Replace JavaScript 101 Section with MDN information using Kuma API

### ISSUE THREAD

**Issue by ajpiano** [jquery/learn.jquery.com#257]
As we discussed in #117, maintaining our own JS 101 section adds overhead to our process and is duplicative of the [MDN](https://developer.mozilla.org/en-US/) JavaScript and DOM resources. However, straight-up linking to MDN (from where?) without actually having basic JS/DOM content on our site to read at the time was an unappealing prospect. What we did not realise at the time is that there is an [API](https://developer.mozilla.org/en-US/docs/Project:The_Kuma_API) for obtaining the content of MDN and using it elsewhere. This seems like a reasonable, nay... awesome, alternative than hosting and maintaining "our own" JS 101 reference and it seems that it would not be difficult to integrate hitting Kuma into our grunt build.

There are a few kinks to be discussed and ironed out, including but not limited to
* Right now the site can be built offline. Adding Kuma means that would not be possible, or at least it would have to be worked around.
* All of our articles can be contributed-to via Git/GitHub (there's a link to the raw markdown in GitHub on each page) - this wouldn't apply to anything we bring in via Kuma and it could be unclear to folks who want to contribute back.
* All of our articles show contributors by using the git commit history of the file -- again, we'd have to eschew this for content we bring in from MDN
* Anything we'd pull from MDN wouldn't be versioned "by us." Our deploys are automated using git webhooks, and tagging with a semver pushes to the live site. If we use MDN, do we just take whatever we happen to pull from the API at build time and call it a day?

In general, however, this does seem like a generally good idea and I'd like to discuss these sticky points further and then see if we can move forward. 

(cc @codepo8)

**Comment by kswedberg** [comment]
:+1 to @dmethvin's comment

**Comment by danheberden** [comment]
If we offer tutorials in the "js 101" camp, then great - but as for technical resource and reference, :+1: to linking to MDN

**Comment by arthurvr** [comment]
Currently the articles are more likely structured as reference than tutorials. Except the `getting started`, but that kind of tutorials are all around the place, so.

My suggestion:

* Remove the hole Javascript 101 section as it is, and replace it with a list of linked handy resources in the right order. That shouldn't be limited to MDN tho.
* On top of that page, include an intro covering what Javascript is and why it's important.
* In the future we can still add real tutorials on raw Javascript.

If you want, I can take that all this week. Keep in mind that would enable us to close a *huge* bunch of issues.

**Comment by dmethvin** [comment]
Sounds like a good way to go then! :smiling_imp:

**Comment by kswedberg** [comment]
sounds great to me, @arthurvr!

**Comment by agcolom** [comment]
:+1:
