### ISSUE TITLE
Sentence cut off on Code Organization Concepts page

### ISSUE THREAD

**Issue by alimony** [jquery/learn.jquery.com#286]
http://learn.jquery.com/code-organization/concepts/

The sentence under the headline Encapsulation ends: "just this effort is sufficient to lend"

How does it really end? :)

**Comment by icode-git** [comment]
maybe we can add "to lend an efficient structure to your code"
or " is sufficient to break a complex problem into small pieces which can be easier to understand and implement"

**Comment by aperala** [comment]
That same sentence fragment also repeats "pieces" in a way that could be confusing.

Maybe, to add to the above:
The first step to code organization is separating pieces of your application into distinct units; sometimes, even just this effort is enough to lend an efficient structure to your code.

**Comment by Krinkle** [comment]
Also reported since in https://github.com/jquery/learn.jquery.com/pull/748.

Closed by https://github.com/jquery/learn.jquery.com/pull/748.
