### ISSUE TITLE
I made a Kindle edition for you guys

### ISSUE THREAD

**Issue by danchoi** [jquery/learn.jquery.com#41]
You can see screenshots and download the Kindle ebook of jQuery Fundamentals here:

https://github.com/danchoi/docs_on_kindle

Let me know if I can do anything else to help on this front. Cheers.

**Comment by driade** [comment]
Hi, hello, good morning. I've just made a program to convert the repo into epub and mobi.

https://github.com/driade/learn-jquery-book

May this help?
