### ISSUE TITLE
About page is out of date

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/learn.jquery.com#569]
It contains gems like:

> The second is docs.jquery.com, that erstwhile chestnut still living out its final days before it will be shut down in early 2013.

Also, regardless of the current state, we should drop the beta section and accompanying banner.

**Comment by arthurvr** [comment]
Maybe we could include a section explaining our long-term plans with the learn site? We had a discussion about it in the meeting. (cc: @AurelioDeRosa @RedWolves)

**Comment by AurelioDeRosa** [comment]
Sure! I think we can combine the info of the blog post I prepared with the general plan described by [@agcolom's document](http://meetings.jquery.org/2015-01-14-content/) and related documents.

**Comment by Krinkle** [comment]
Mention of beta removed in https://github.com/jquery/learn.jquery.com/pull/707.
Mention of docs.jquery.com updated in https://github.com/jquery/learn.jquery.com/commit/c5962fd600b0237cb2ceca412e304a3f3c1e889b.
