### ISSUE TITLE
JS101 Improvements

### ISSUE THREAD

**Issue by connor** [jquery/learn.jquery.com#58]
From a high-level, this is good since code can (sometimes) communicate quicker and more directly than words explaining that code. However, it feels like a lot of the sections in JavaScript101 could use some supporting text (and page structure - to make it more palatable, like `<h3>`'s, paragraph breaks, etc...). The ones in particular are:

- [testing type](http://stage.learn.jquery.com/javascript-101/testing-type/)
- [scope](http://stage.learn.jquery.com/javascript-101/scope/)
- [the this keyword](http://stage.learn.jquery.com/javascript-101/this-keyword/)

---
What are people's thoughts on stuff like this? Should we use more text to explain it? I think so, but would love some other opinions (esp those on the jQuery team).

If you all agree, I'd be happy to rock out first versions of revisions.

**Comment by arthurvr** [comment]
@ghost @connor One of you interested in picking this up again?
