### ISSUE TITLE
Grunt Build Error: Need to add attribution meta tag to be able to build a brand new page

### ISSUE THREAD

**Issue by RedWolves** [jquery/learn.jquery.com#590]
This one took me quite some time to narrow in on it. 

If you create a new page and try to do a `grunt deploy` or a `grunt build` you get an error 

    Fatal error:  Cannot read property '1' of null

I was able to figure out that the line that's throwing the error is in the [Gruntfile.js line 59-80](https://github.com/jquery/learn.jquery.com/blob/master/Gruntfile.js#L59-L80)

    contribs = result.trimRight().split( /\r?\n/g )

			// Reduce to a unique list of contributors
			.filter(function( value, index, array ) {
				return array.indexOf( value ) === index;
			})

			// Convert to structured objects
			.map(function( contributor ) {
				var matches = parseRE.exec( contributor );
				return {
					name: matches[ 1 ].trim(),
					email: matches[ 2 ]
				};
			})

			// Alphabetize by 'last name' (relatively crude)
			.sort(function( a, b ) {
				return a.name.split( " " ).pop().toLowerCase() <
					b.name.split( " " ).pop().toLowerCase() ?
					-1 : 1;
			});

To get around this I HAVE to add an `attribution` meta tag:

    <script>{
	"title": "Title",
	"level": "beginner",
	"attribution": [
		"Ralph Whitbeck <ralph@mail.com>",
	]
    }</script>

Which if we look at the [style guides](https://learn.jquery.com/style-guide/) `attribution` should be optional. 

Seems like this [commit](https://github.com/jquery/learn.jquery.com/commit/47c2b40c8832547cf46ea0be37a6e73cd250d8ba) by @scottgonzalez introduced this new code and potentially the bug.  I am not sure what's going on there enough to tell you what the actual problem is though.

**Comment by scottgonzalez** [comment]
I'd like to hear your thoughts on the contribution listings. I've file #602 for a discussion about that.
