### ISSUE TITLE
Improve traversing section

### ISSUE THREAD

**Issue by addyosmani** [jquery/learn.jquery.com#6]
**Original ticket:**

The traversing section is extremely brief and not that informative; it's an area that students in my online class struggled with, and the book's not a great resource as it stands.

and here's a direct link to the traversing section:

https://github.com/jquery/web-learn-jquery-com/blob/master/content/jquery-fundamentals/jquery-basics/traversing.md

**Notes:**

Many of the existing posts by others I've found on traversing while doing a cursory search for this ticket don't appear to be that comprehensive. It might be easier for us to write out something a little more complete from scratch as it shouldn't take long. 

Anyone want to tackle it?

**Comment by CarstenP** [comment]
Shouldn't the order in the find example (line 8 in  the code in chapter "Children" ) be like this?

// returns [ div.parent, div.child, div.surrogateParent1, div.surrogateParent2 ]
