### ISSUE TITLE
Reconsider attribution on all pages

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/learn.jquery.com#602]
The bottom of every article shows a list of contributors, but the list doesn't actually provide much value. The lists also include people who have made just a single typo fix, or even someone who only touched the metadata, but didn't contribute to the article at all.

I'd like to propose that we just remove this and only include references to external content where appropriate.

**Comment by arthurvr** [comment]
I agree on everything you said, but on the other hand having totally no attribution isn't friendly to contributors too. Isn't there a way the team can decide who needs to be in the attributions? Or display the most frequent writers/contributors in the about page.

I do really think something must be changed tho

**Comment by scottgonzalez** [comment]
Manually maintaining a list of contributors per article is too cumbersome. Listing the most frequent contributors will leave out attribution for someone who writes an entire article, or even two, about a specific topic. Basically, I think if we do any attribution, it's either going to be too much or too little. We can always just link to https://github.com/jquery/learn.jquery.com/graphs/contributors and add a thanks to all of the contributors on http://learn.jquery.com/about/.

**Comment by arthurvr** [comment]
> We can always just link to https://github.com/jquery/learn.jquery.com/graphs/contributors and add a thanks to all of the contributors on http://learn.jquery.com/about/.

Yeah but that's not really accurate too, I mean, somebody that fixed 10 types comes over as having done more than somebody that wrote 9 articles.

**Comment by scottgonzalez** [comment]
Right, and I don't think we want to get into determining those metrics, which is why I don't want to list contributions.

**Comment by dmethvin** [comment]
This definitely seems like too much manual work. GitHub provides all sorts of tools for determining who contributed, so let's just fall back to letting people use those even if they are imperfect.

**Comment by agcolom** [comment]
I agree with Scott that the current system isn't ideal. I like the idea of having a link to a full listing of contributors on the about page, or having the full listing at the bottom of that page. We could do that by additions rather than commit if there was a consensus that this was more representative of the amount of contribution (https://github.com/jquery/learn.jquery.com/graphs/contributors?from=2010-11-07&to=2015-01-03&type=a). I have no strong feeling either way.

**Comment by arschmitz** [comment]
If we are going to list anything i think the graphs @agcolom links to for the number lines added is probably the best metric we have available without additional work.

**Comment by arthurvr** [comment]
Seems fine. Let's go for graphs based on additions.

**Comment by scottgonzalez** [comment]
I'm not sure why we would go through the work of generating the graphs on our own page instead of linking to the existing graphs.

**Comment by arthurvr** [comment]
I'd go for linking them up too, easier and more maintainable for us. Plus that linking to github will highlight it once again that people can contribute to this kind of sites. Are PRs welcome?

**Comment by arschmitz** [comment]
I was talking about just linking to them.

**Comment by scottgonzalez** [comment]
I know everyone else was referring to just links, I was just commenting on:

> I like the idea of having a link to a full listing of contributors on the about page, or having the full listing at the bottom of that page.

Though reading it again, I realize @agcolom may have just meant an actual listing and not graphs or counts.

@arthurvr Seems like everyone is on board with a PR at this point :-)

**Comment by agcolom** [comment]
Yes, I never meant having a graph or counts. just a link or list of names.

**Comment by arthurvr** [comment]
Just created 2 PRs to fix this. (https://github.com/jquery/jquery-wp-content/issues/334 and https://github.com/jquery/learn.jquery.com/issues/603)

**Comment by scottgonzalez** [comment]
Overall, I'd say the two PRs look good, but my concern is that we're no longer linking to the original content when we have the data. I don't think we did a great job with this before though. It was certainly non-obvious.

**Comment by arthurvr** [comment]
For those interested, recent discussion in `#jquery-content`: http://irc.jquery.org/%23jquery-content/latest.log.html#t08:24:21. We didn't make a final decision tho. Any more opinions on this? 

What to do with licensing issues? Are there actually issues?

**Comment by scottgonzalez** [comment]
Let's address that separately since it's not directly tied to the full contributor list.

**Comment by arthurvr** [comment]
:+1:

**Comment by arthurvr** [comment]
Other review, or ready to merge?
