### ISSUE TITLE
Try Jqwery step error

### ISSUE THREAD

**Issue by germanigortcev** [jquery/learn.jquery.com#604]
https://www.dropbox.com/s/zsv3arsrnfka6lh/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-04%2012.29.02.png?dl=0

I writed is true answer but i have error.

**Comment by arthurvr** [comment]
This is the repository for the jQuery learning center (`learn.jquery.com`), so this isn't something that should be reported there.

To report issues with `try.jquery.com`, click `report a bug` in the corner of that website:

![code_school_-_try_jquery](https://cloud.githubusercontent.com/assets/6025224/5605387/83fd159c-93f8-11e4-8c59-55e6054eab62.png)

**Comment by agcolom** [comment]
Closing as not related to the learning center
