### ISSUE TITLE
"Feature & Browser Detection" article needs an update

### ISSUE THREAD

**Issue by arthurvr** [jquery/learn.jquery.com#610]
Reading this article it seemed like kinda outdated. Some points:

* First upcoming thought: in fact the article isn't jQuery related, except the part about `$.support`.
* Yepnope is deprecated. Let's not recommend it anymore.
* We [shouldn't recommend `Modernizr.load`](https://github.com/Modernizr/Modernizr/issues/1182), as it will be removed in Modernizr v3.
* About the `Helpful Articles` section, aren't there more up-to-date articles these days?

Thoughts? I'm wanting to update the article in a PR.

**Comment by dmethvin** [comment]
All of the discussion on `$.support` should be removed since we've deprecated and removed it.

Removing the mention of yepnope would be fine with me.

The rest should be refreshed to 2015 vintage, since even the example is talking about an ancient Chrome user agent string.

**Comment by arthurvr** [comment]
Agreed on all of that. One big PR or smaller focussed ones?

**Comment by dmethvin** [comment]
A single PR works for me.

On Sun, Jan 11, 2015 at 5:25 PM, Arthur Verschaeve <notifications@github.com

**Comment by arthurvr** [comment]
@dmethvin Would you mind reviewing my PR (#616)? It removes the deprecated stuff and updates the current content to 2015 vintage. The article is thereafter still open for improvements tho.
