### ISSUE TITLE
Array.slice() method documentation needs correction

### ISSUE THREAD

**Issue by obokaiwele** [jquery/learn.jquery.com#611]
At http://learn.jquery.com/javascript-101/arrays/#slice-
The documentation says "This method takes one parameter, which is the starting index", however this method takes an optional second parameter which is the ending index https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

**Comment by arthurvr** [comment]
PR is #612
