### ISSUE TITLE
Part of the Learning site is down!

### ISSUE THREAD

**Issue by ssedwards1** [jquery/learn.jquery.com#625]
It would look like everything in the Javascript 101 section is not available?

Example: http://learn.jquery.com/javascript-101/loops/

**Comment by arthurvr** [comment]
It's just [removed](https://github.com/jquery/learn.jquery.com/pull/622).

**Comment by dmethvin** [comment]
Was there a link to it somewhere on our site? Or did you just come in through Google or some other site?

**Comment by arschmitz** [comment]
@dmethvin i'm sure there are links to this content on many sites. Any time we remove content from any site we should really be setting up redirects ( even if its just to the front page )

**Comment by dmethvin** [comment]
Mainly I was wondering if we missed one ourselves, but yes it seems like these should at least redirect to the main  page or something.

**Comment by ssedwards1** [comment]
That explains that then :-) To answer how I got here, i think it was from a google search.

**Comment by ajpiano** [comment]
We probable need to 302 everything in javascript 101?

**Comment by CousinHubert** [comment]
@arthurvr : Thank you Arthur for replying quickly. I enjoyed what I'd read a while ago on "Javascript 101", and I regret its removal, but after reading the reasoning in #257, I also understand why it has been removed, and agree that the Mozilla Developper Network is a good resource. I will turn to MDN, for now, and come back to learn.jquery.com when I'm ready.
