### ISSUE TITLE
Contributing page needs update

### ISSUE THREAD

**Issue by gnarf** [jquery/learn.jquery.com#629]
In particular, the meeting time in the [getting help](http://learn.jquery.com/contributing/#getting-help) section is wrong.

> In addition, the jQuery Content Team holds a public, weekly meetings on Freenode, at 1PM Eastern time in the #jquery-meeting channel.

It doesn't even say what day, also it's biweekly, maybe just link to the meetings calendar? http://meetings.jquery.org/

**Comment by arthurvr** [comment]
I was waiting for https://github.com/jquery/learn.jquery.com/issues/554 to be figured out, but you're true, time to give it an update. I'll do it Monday.

**Comment by arthurvr** [comment]
@gnarf I opened #631. Could you review?
