### ISSUE TITLE
bower page for jquery.ui - there is no jquery-ui.js or jquery-ui.min.js

### ISSUE THREAD

**Issue by gotofritz** [jquery/learn.jquery.com#630]
Hi. In this page here https://github.com/jquery/learn.jquery.com/blob/master/page/jquery-ui/environments/bower.md , it talks about the jquery-ui.min.js file you get when downloading jquery-ui with bower 

    │       ├── jquery-ui.js
    │       └── jquery-ui.min.js

Those files are not there for 1.11.3. What gives?

**Comment by arthurvr** [comment]
For me it seems like everything works fine.

```
.
└── bower_components
      └── jquery-ui
        ├── AUTHORS.txt
        ├── LICENSE.txt
        ├── README.md
        ├── bower.json
        ├── component.json
        ├── composer.json
        ├── jquery-ui.js
        ├── jquery-ui.min.js
        ├── package.json
        ├── themes
        │   ├── base
        │   │   ├── accordion.css
        │   │   ├── all.css
        │   │   ├── autocomplete.css
        │   │   ├── base.css
        │   │   ├── button.css
        │   │   ├── core.css
        │   │   ├── datepicker.css
        │   │   ├── dialog.css
...
```

Did bower throw any errors when running `bower install`? Can you check if other files are downloaded?

**Comment by gotofritz** [comment]
I was installing jquery.ui instead of jquery-ui - they seem to be different

**Comment by arthurvr** [comment]
Indeed, makes sense.
