### ISSUE TITLE
Permalinks found on the footer of articles

### ISSUE THREAD

**Issue by najela** [jquery/learn.jquery.com#647]
From the logs here, http://jenkins.jquery.com/job/stage.learn.jquery.com/lastBuild/console,

The footer of articles such as http://stage.learn.jquery.com/code-organization/dont-repeat-yourself/  have links to other articles given by URLs such as http://stage.learn.jquery.com/?page_id=4729 instead of a URL's like http://stage.learn.jquery.com/code-organization/feature-browser-detection/

Is this intentional?

**Comment by arthurvr** [comment]
https://github.com/jquery/jquery-wp-content/blob/master/themes/learn.jquery.com/content-page.php#L31

@scottgonzalez I didn't do any serious wordpress work for years, do you have an idea how to change these to echo to the normal links?

**Comment by sigorilla** [comment]
Hi @arthurvr @najela 
Instead of this code
```php
<?php echo $next_prev_arr['next']->guid; ?>
``` 
we can use 
```php
<?php echo get_page_link($next_prev_arr['next']->ID); ?>
```
