### ISSUE TITLE
It is odd when using "attr" on checkbox, it works on the first time only

### ISSUE THREAD

**Issue by LeonLi0102** [jquery/learn.jquery.com#652]
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Checkbox Test</title>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script>
	$().ready(function(){		
		$("#checkControl").click(function(){			
			// It is odd it works only on the first time whey you click 'All/None'  
			 $("input[name='check_items']").attr("checked",this.checked);
			 
			// I know this will work, but still the code above is confused me.
			// $("input[name='check_items']").prop("checked",this.checked);
			 
		});		
	});		
	</script>
</head>
<body>
<input type="checkbox" id="checkControl" >All/None<br /><br />
<input type="checkbox" name = "check_items" >item1<br />
<input type="checkbox" name = "check_items" >item2<br />
</body>
</html>

**Comment by najela** [comment]
@LeonLi0102 Please can you provide a test case? Everything works fine here http://jsfiddle.net/129d9ubc/1/

**Comment by scottgonzalez** [comment]
Please read the documentation about boolean attributes on http://api.jquery.com/attr/.

**Comment by LeonLi0102** [comment]
<pre>
<textarea>
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Checkbox Test</title>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script>
	$().ready(function(){		
		$("#checkControl").click(function(){			
			// It is odd it works only on the first time whey you click 'All/None'  
			 $("input[name='check_items']").attr("checked",this.checked);
			 
			// I know this will work, but still the code above is confused me.
			// $("input[name='check_items']").prop("checked",this.checked);
			 
		});		
	});		
	</script>
</head>
<body>
<input type="checkbox" id="checkControl" >All/None<br /><br />
<input type="checkbox" name = "check_items" >item1<br />
<input type="checkbox" name = "check_items" >item2<br />
</body>
</html>
</textarea>
</pre>

**Comment by najela** [comment]
@LeonLi0102  Please read the documentation pointed by @scottgonzalez  and you'll understand

**Comment by LeonLi0102** [comment]
Thanks!
