### ISSUE TITLE
text() as a getter returns all not only the first element as suggested by the first paragraph

### ISSUE THREAD

**Issue by zeasratwde** [jquery/learn.jquery.com#655]

**Comment by arthurvr** [comment]
First paragraph on which page?

**Comment by zeasratwde** [comment]
the frist paragraph in this page http://learn.jquery.com/using-jquery-core/working-with-selections/

**Comment by AurelioDeRosa** [comment]
@zeasratwde in the specified page there isn't a reference to `text()`. Can you please double check?

**Comment by arthurvr** [comment]
@AurelioDeRosa There actually is a sentence we can clarify:

> Getters get the requested value only for the first element in the selection.

**Comment by AurelioDeRosa** [comment]
@arthurvr I didn't say there is nothing to improve. I pointed out that the page doesn't discuss the `text()` method.

**Comment by arthurvr** [comment]
If the page mentions "getters" that points to text() as well ;)

**Comment by zeasratwde** [comment]
I couldn't stop reading the tutorial. What an excellent find? Great work!
