### ISSUE TITLE
Update UI AMD article to match download structure

### ISSUE THREAD

**Issue by jzaefferer** [jquery/learn.jquery.com#659]
As pointed out by https://github.com/jquery/learn.jquery.com/pull/462#issuecomment-104412695 we [currently list individual files](https://github.com/jquery/learn.jquery.com/blob/master/page/jquery-ui/environments/amd.md#directory-structure) in the "using with AMD" article. Our downloads don't include individual source files anymore, so that needs to be updated.

@tjvantoll is that something you could look into?

**Comment by tjvantoll** [comment]
Sure. I just sent a PR https://github.com/jquery/learn.jquery.com/pull/660.
