### ISSUE TITLE
Optimize Selectors: qSA before Sizzle

### ISSUE THREAD

**Issue by mr21** [jquery/learn.jquery.com#666]
Hi :)

On this page: https://learn.jquery.com/performance/optimize-selectors/

We can read this:
`$( "#container div.robotarm" );` is slower than:
`$( "#container" ).find( "div.robotarm" );`

But **dmethvin** said `jQuery` is testing if `querySelectorAll`  throw an error before using `Sizzle`.

I made a quick test (with a recent jQuery) and the result is the reverse of what this page is saying.

I suppose we have to write a warning about using the non-standard selector like `:contains, :eq, :first` etc.

Do you want me to make a PR to rewrite this (if you agree) ?

EDIT: I really dislike the number of this issue :smiling_imp:

**Comment by arthurvr** [comment]
Thanks for the report! Can someone from the core team weigh in on this? Cc: @timmywil @dmethvin @gibson042

**Comment by gibson042** [comment]
@Mr21 is right; nonstandard selectors are by far the biggest performance risk. `.find` would only help if it segregates a nonstandard portion. PR welcome.
