### ISSUE TITLE
Please check if avoid-conflicts-other-libraries doc is valid in last 2 examples

### ISSUE THREAD

**Issue by makmi** [jquery/learn.jquery.com#673]
Why in last 2 examples of learn.jquery.com/page/using-jquery-core/avoid-conflicts-other-libraries.md there is prototype.js included after jquery.js and still $ is referencing a jQuerys short-cut function ?

**Comment by scottgonzalez** [comment]
Those are examples of what the header says: Use the Argument That's Passed to the jQuery( document ).ready() Function.

Feel free to suggest additional wording to clarify the use in a pull request.
