### ISSUE TITLE
'$' unexplained

### ISSUE THREAD

**Issue by Dimpl** [jquery/learn.jquery.com#680]
As a newcomer to jQuery, I had to search StackOverflow to discover that $ is shorthand for 'jQuery'

**Comment by hatzopoulos** [comment]
There's a mentioning of it in [Avoiding Conflicts with Other Libraries](http://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/).

Perhaps it wouldn't hurt to also mention it in either [How jQuery works](http://learn.jquery.com/about-jquery/how-jquery-works/) or as an earlier page in the Using jQuey Core section.
