### ISSUE TITLE
Separate http/s redirects

### ISSUE THREAD

**Issue by OmgImAlexis** [jquery/learn.jquery.com#690]
I've noticed this on quite a few links. I'm assuming you guys do http and https redirects separately?

`http://docs.jquery.com` redirects to `https://learn.jquery.com`
`https://docs.jquery.com` redirects to `https://jquery.com`

**Comment by arthurvr** [comment]
Hmm, looks like the right behaviour would be to redirect to `learn.jquery.com`. @gnarf Do you have any idea?

**Comment by gnarf** [comment]
I bet the redirection site doesn't have HTTPS enabled, so it reverts to
redirecting to jQuery.com I'll take a look at this early next year, feel
free to ping remind me if I don't, my plate is filling up with stuff to
remember pretty quick.

Thanks for the report!

**Comment by arthurvr** [comment]
Thanks @gnarf!

**Comment by gnarf** [comment]
Also, @omgimalexis where else have you seen it? I imagine fixing it in one place will cover almost all of them, but want to make sure

**Comment by OmgImAlexis** [comment]
@gnarf this is across multiple different repos you in the jQuery org.

**Comment by gnarf** [comment]
If you could give me a short list of known bad redirects it would make sure
I can fix them all at once...

**Comment by arthurvr** [comment]
Hey @OmgImAlexis, would you mind telling us what other bad redirects you've seen? Thanks! :)

**Comment by OmgImAlexis** [comment]
@arthurvr https://github.com/jquery/jqueryui.com/pull/140 https://github.com/jquery/meetings.jquery.org/pull/28 https://github.com/jquery/jquery.org/pull/117 https://github.com/jquery/api.jquery.com/pull/841
