### ISSUE TITLE
Can't Get Previous page URL using jQuery

### ISSUE THREAD

**Issue by Parthiangularjs** [jquery/learn.jquery.com#695]
Hi,
   I have facing an issue for getting previous page url while using document.referrer property using JQuery.
When i'm going to click back button on current UI page(page2.html), it'll go to the previous page(page1.html) but again i want to come back to the current page(page2.html), It'll work instated of before clicking the back button i press f5 key, here the document.referrer property value is getting empty so that i can't get back to the current page. If anybody knows this issue kindly let me know how can i fix?

Thanks & regards,
Parthi

**Comment by dmethvin** [comment]
Hi Parthi, this is a good question for a forum like StackOverflow.com . This is the issue tracker for the web site so it's off topic here.
