### ISSUE TITLE
Optimizing selectors is wrong?

### ISSUE THREAD

**Issue by franciscop** [jquery/learn.jquery.com#697]
Hello everyone, I made [an alternative to jquery](http://umbrellajs.com/) and was testing it against jquery for performance. I also wanted to test the most optimized jquery selectors and ended up in [jquery's Optimize Selectors page](https://learn.jquery.com/performance/optimize-selectors/). However, when testing it in Phantom JS (based on webkit), this doesn't seem to hold true:

```js
$( ".buttons > *" ); // Extremely expensive.
$( ".buttons" ).children(); // Much better.
```

The first one seems to be faster for my situation. This is the test that should fail if jquery's page is true:

```js
it("jquery vs jquery: mistake?", function() {
    
  var aTime = performance(function(){
    $(".ro > *");
  }, 100);
    
  var bTime = performance(function(){
    $(".ro").children();
  }, 100);
    
  console.log('a: ' + aTime + 'ms ', 'b: ' + bTime + 'ms');
    
  expect(aTime).to.be.below(bTime, uTime + ' ms');
});
```

However the test passes and in the terminal it's printed:

```
a: 203ms  b: 369ms
```

In the browser, the test also passes and it's "wrong":

```
a: 217ms  b: 264ms
```

So, was it an optimization for a previous version? is it a wrong optimization? Or it's just that it depends on the situation? (therefore, it's wrong stating it as an optimization)

**Comment by staabm** [comment]
Did you observe the same measurements in real browsers?

**Comment by franciscop** [comment]
Yes, but unfortunately I only tested Firefox (I forgot in Chrome), which is the second console message:

```text
a: 217ms  b: 264ms
```

However I forgot to test it in Chrome, but maybe it's similar to webkit in Phantom JS? I can test it in IE11 and Chrome later on, should this be enough?

**Comment by dmethvin** [comment]
I think this is another case where improvement in browsers over time has changed the results. The best advice for selectors today is to keep them simple (Avoid Excessive Specificity), don't use jQuery selector extensions (needs to be added), and that's about it. Perhaps we can just delete the rest.

**Comment by scottgonzalez** [comment]
Rather than deleting the rest, it would be good to document the history so that this can also serve as a resource to show that these behaviors are no longer necessary rather than just omitting them.

**Comment by kswedberg** [comment]
@dmethvin Do we want to say "don't use jQuery selector extensions"? Or should we say "use jQuery selector extensions sparingly"? Or "be careful when using complex selectors or jQuery selector extensions, and if you notice performance issues with your code, check there first"? I could be way off base, but I generally feel uncomfortable using such absolute statements, and I think using `:visible` or `:hidden` or even `:odd` can come in handy from time to time when used judiciously.

**Comment by scottgonzalez** [comment]
I agree that custom selectors are really nice and shouldn't be avoided completely. It all depends on context; if you're not in a hot path, it's unlikely to matter what selector you're using.

**Comment by franciscop** [comment]
The whole `optimizing selectors` section seems to be for people who are actually having issues with the performance, so I'd say to target them in the way we speak. Saying *be careful when using complex selectors or jQuery selector extensions, and if you notice performance issues with your code, check there first* seems redundant for this public.

But I also agree that absolutes are uncomfortable since they make people do completely weird things to avoid them, while in most situations are fine. What about just stating it? Like:

> jquery selectors such as :visibly, :odd, etc have a performance penalty associated with them

**Comment by dmethvin** [comment]
If the point is to give people help for cases where selectors end up being a bottleneck, the page should help to determine when that is the case. Right now it seems to be encouraging blind rules when (if the data from @franciscop is correct) the rules have changed. There are some pretty clear signs when `:visible` causes perf degradation, you can look for the yellow exclamation point in Chrome for example. I don't know whether you want to go into that detail on a page like this though?

**Comment by kswedberg** [comment]
I just updated the page at https://github.com/jquery/learn.jquery.com/pull/704. @dmethvin, @franciscop, @scottgonzalez: let me know if you think it sufficiently addresses all the concerns noted here.
