### ISSUE TITLE
What is dfd?

### ISSUE THREAD

**Issue by JoeKahl** [jquery/learn.jquery.com#699]
What does the parameter dfd represent?
prepareInterface does not get dfd as an input parameter.
So where does dfd come from and what does it represent?
I looked at the API for $.Deferred and there is nothing about an input parm except for beforeStart.
If dfd is beforeStart then is it automatically provided by $.Deferred?  I am trying to use this coding pattern and I cannot read nor understand this aspect of the code.  
The text explaining the code includes nothing about dfd.
Please help me catch up on this jQuery capability.
@JoeKahl

function prepareInterface() {
    return $.Deferred(function( **dfd** ) {
        var latest = $( ".news, .reactions" );
            latest.slideDown( 500, dfd.resolve );
            latest.addClass( "active" );
    }).promise();
}

$.when(
    getLatestNews(),
    getLatestReactions(),
    prepareInterface()
).then(function() {
    console.log( "fire after requests succeed" );
}).fail(function() {
    console.log( "something went wrong!" );
});

**Comment by AurelioDeRosa** [comment]
Hi @JoeKahl.

From the [$.Deferred documentation](http://api.jquery.com/jQuery.Deferred/):

> The jQuery.Deferred method can be passed an optional function, which is called just before the method returns and is passed the new deferred object as both the this object and as the first argument to the function.

So, `dfd` is the new `Deferred` object the `$.Deferred` function is creating.
