### ISSUE TITLE
`javascript-101/types` needs to be expanded

### ISSUE THREAD

**Issue by ajpiano** [jquery/learn.jquery.com#70]
Import the old mediawiki content from http://docs.jquery.com/Types and migrate it in with the existing page.

**Comment by arthurvr** [comment]
> We should merge this page and the testing types page and discuss the new $.type in the combined page.

PR https://github.com/jquery/learn.jquery.com/pull/597.

**Comment by arthurvr** [comment]
> We've already put it on http://api.jquery.com/Types/ and have updated it there, so better to get it from there.

Should we have duplicate content then? Shouldn't we just link to the api site? Or they to us?
