### ISSUE TITLE
Selecting Elements: "Multiple Selector" missing

### ISSUE THREAD

**Issue by awehring** [jquery/learn.jquery.com#702]
A very basic request. 
At the beginning of "Selecting Elements" the "Multiple Selector" should be added, I think.

It is the place where a beginner (like me) looks and I only discovered it in the API (guessing that jQuery works like CSS).

**Comment by agcolom** [comment]
This refers to http://learn.jquery.com/using-jquery-core/selecting-elements/
@awehring Thanks very much for this suggestion. I think this is a good point and I will bring this issue to our next content meeting (next week). Please feel free to make a pull request in the meantime if you like.

**Comment by awehring** [comment]
Thank's a lot. I appreciate your effort - and the effort of everybody involved in the  jQuery development - VERY much.

**Comment by AurelioDeRosa** [comment]
@agcolom is this one of the issues you mentioned that @kswedberg was going to pick? If not, I can take it.

**Comment by kswedberg** [comment]
@AurelioDeRosa : yeah, I got it. thanks!
