### ISSUE TITLE
Selecting by ID that has CSS special characters

### ISSUE THREAD

**Issue by xerces8** [jquery/learn.jquery.com#715]
The page [How do I select an element by an ID that has characters used in CSS notation?](http://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/) could also mention a simple solution that is also faster:

    // Does not work:
    $( "#some:id" )

    // solution with no string replacement:
    $( document.getElementById("some:id"))

**Comment by AurelioDeRosa** [comment]
The aim of the page is to teach jQuery, not the methods of the DOM API. I don't think we should perform any action here. Also, jQuery is quite smart in how it handles selectors like these, so the native approach is not that faster than passing through jQuery.

I'm closing this issue for now but I'm happy to reopen it if someone of the team disagrees.

**Comment by xerces8** [comment]
The point is not that it is faster, but simpler. A single (a bit long, true) function call instead of needing to write and use an extra function*, or to escape the string manually (which is error prone).

* - OTOH a function like that to do escaping would be nice to have included in jQuery

**Comment by dmethvin** [comment]
https://jquery.com/upgrade-guide/3.0/#feature-new-method-jquery-escapeselector
