### ISSUE TITLE
Setting the selected option using prop() vs attr() in IE

### ISSUE THREAD

**Issue by Lukapt** [jquery/learn.jquery.com#717]
Hi all,

I'm having a problem selecting options and reading when using both prop() and attr() methods. I reduced the problem to what could be seen in the following fiddler:
https://jsfiddle.net/kz3nskf6/1/

Basically after setting the property of all options to false I can't set a selected property using $.attr() method and then read the select value with $.val(). The problem only occurs in IE11 (I haven't tried other versions).

While this may seem an odd thing to do I got here since I'm using different jQuery plugins to enhance my selects (multiselect and picklist). I can't programatically clean all selected options by using the prop() method because later on the multiselect will not work anymore but I can't also just use the attr() method since the multiselect uses the prop().

I'm not sure if this is a bug or simply a browser limitation (or even the intended behavior). Chrome and Firefox seem to handle that just fine.

I tried several different jQuery versions but without luck.

Thanks in advance for your help.

**Comment by Lukapt** [comment]
Sorry, I thought I was submitting the issue to jQuery Core repository.

I already created a new one: https://github.com/jquery/jquery/issues/3180

Please disregard this ticket.

**Comment by agcolom** [comment]
@Lukapt Thanks for letting us know. I'll close this ticket :-)
