### ISSUE TITLE
use jQuery.escapeSelector

### ISSUE THREAD

**Issue by HolgerJeromin** [jquery/learn.jquery.com#724]
http://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/ 
should suggest jQuery.escapeSelector for jQuery 3

**Comment by AurelioDeRosa** [comment]
Considering that jQuery 3 has not been around for a long time, I'd add the jQuery 3 way first but keep the old way. Any other opinion on this?

**Comment by Krinkle** [comment]
Fixed in https://github.com/jquery/learn.jquery.com/pull/765. Will be live on the next publication tag.
