### ISSUE TITLE
Sample code generates error in 3.1.1 but not in 2.4.4

### ISSUE THREAD

**Issue by mrbroschat** [jquery/learn.jquery.com#735]
<!DOCTYPE html>
<html>
<head>
    <script src="jquery-3.1.1.js"></script>
    <script>
    $( document ).ready(function() {
        console.log( "document loaded" );
    });

    $( window ).load(function() {
        console.log( "window loaded" );
    });
    </script>
</head>
<body>
    <iframe src="http://michaelbroschat.com"></iframe>
</body>
</html>
Both Edge and Chrome report:
jquery-3.1.1.js:9793 Uncaught TypeError: url.indexOf is not a function(…)jQuery.fn.load @ jquery-3.1.1.js:9793(anonymous function) @ testCore1.html:10
testCore1.html:7 document loaded

**Comment by dmethvin** [comment]
Dup of #738
