### ISSUE TITLE
event delegation

### ISSUE THREAD

**Issue by anandSant24** [jquery/learn.jquery.com#742]
https://learn.jquery.com/events/event-delegation/

In the link above it says: 
Event delegation allows us to attach a single event listener, to a parent element, that will fire for all descendants matching a selector, whether those descendants exist now or are added in the future.

I think this line needs to be corrected ?
whether those descendants exist now or are added in the future.

"If the descendants exist now" is a valid case but if they "are added in future" is not valid as the handler will not get fired, although this has been explained later in the same page,can you look into this.

thanks
Anand

**Comment by AurelioDeRosa** [comment]
Hi.

The handler will actually fire. Event delegation is an old technique used in many applications. If you don't trust my words, I've prepared a quick demo for you: https://jsfiddle.net/9x72b74a/

**Comment by anandSant24** [comment]
Hi,

Thanks for the reply, I am familiar with this old technique, In the jsfiddle link you have added handler to the button element not to its parent, here is the example that will not work
https://jsfiddle.net/anand24/9x72b74a/1/ , 

ref: https://learn.jquery.com/events/event-delegation/

and as per the page description and I quote,
"If we were to click our newly added item, nothing would happen. This is because of the directly bound event handler that we attached previously. Direct events are only attached to elements at the time the .on() method is called. In this case, since our new anchor did not exist when .on() was called, it does not get the event handler."
