### ISSUE TITLE
missing text

### ISSUE THREAD

**Issue by taoliu12** [jquery/learn.jquery.com#744]
The first step to code organization is separating pieces of your application into distinct pieces; sometimes, even just this effort is sufficient to lend ???????????????????

https://learn.jquery.com/code-organization/concepts/

**Comment by AurelioDeRosa** [comment]
Thank you for reporting the broken sentence. Without knowing the original intention of the author is hard to tell what the conclusion of the sentence was. However, I think this should made it:

> The first step to code organization is separating pieces of your application into distinct pieces; sometimes, even just this effort is sufficient to improve the structure of your code and its maintainability.

Any opinion?

**Comment by ramyashankaran** [comment]
I am a first-timer with contributing on Github. The complete sentence by @AurelioDeRosa  looks correct for   the topic of encapsulation. Can I take a shot at updating this page?

**Comment by AurelioDeRosa** [comment]
Hi @ramyashankaran.

Yes, we love contributions. Go for it.
