### ISSUE TITLE
parentsUntil does not work if parent id is used and includes "#"

### ISSUE THREAD

**Issue by JohannBlake** [jquery/learn.jquery.com#760]
The code example shows the following:

`$( "span.subchild" ).parentsUntil( "div.grandparent" );`

If the grandparent's id is used instead, you cannot use "#". Example:

`$( "span.subchild" ).parentsUntil( "#grandpa");`

But it will find it if you leave out the "#":

`$( "span.subchild" ).parentsUntil( "grandpa");`

This is inconsistent with the way selecting elements by id works with jQuery. Either fix this or indicate this issue in the documentation.

**Comment by dmethvin** [comment]
> The code example

Can you provide a link to the page you are referring to that is here on learn.jquery.com?

**Comment by JohannBlake** [comment]
Here's the link: [https://learn.jquery.com/using-jquery-core/traversing/](https://learn.jquery.com/using-jquery-core/traversing/)

**Comment by dmethvin** [comment]
There isn't an ID on that element so I'm not sure what you're doing. Do the examples as shown work for you? If not it's something we would handle here in this repo and I can reopen the ticket. If it's something else, you should first ensure there is a problem by having others look at it in a place like StackOverflow. If it is confirmed to be some kind of bug you can report it to https://github.com/jquery/jquery/. You'll need to include an example on a site like jsbin.com or jsfiddle.net demonstrating the problem.

**Comment by JohannBlake** [comment]
You misunderstood. Try an example WITH an id instead of using a class name. parentsUntil will not find a parent if you specify an id instead of a class name.

**Comment by dmethvin** [comment]
Do you mean you have an example like that not on the learn.jquery.com site? Can you link to it?
