### ISSUE TITLE
jQuery is not working/ loading

### ISSUE THREAD

**Issue by tavaksk** [jquery/learn.jquery.com#764]
Hello. I started learning jQuery and it wasn't working. BTW I am using Google Chrome but I also tried in Mozilla. Here is the code:
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Home</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300">
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <link rel="stylesheet" href="css/style2.css">
</head>
<body>

  <div id="welcome">
  <h1>Welcome</h1>
</div>
  <section id="wrapper" class="skewed">
    <div class="layer bottom">
      <div class="content-wrap">
        <div class="content-body">
          <h1>Look Sharp</h1>
          <p>Lorem ipsum dolor sit amer consectetur adipisicing elit. Aut quisquam temporibus dolore vero reiciendis atque debitis. Sequi at consequatur deserunt?</p>
        </div>

        <img src="split-screen/img/pc1.png" alt="">
      </div>
    </div>
  </section>
  <script src="js/main.js"></script>
  <script>
  $(document).ready(function(e) {
    ('#welcome').hide(1).show(100);
  });
  </script>

</body>
</html>

I tried remove "hide" and also use "fadeIn".

**Comment by dmethvin** [comment]
This is the bug tracker for issues with the learn.jquery.com site. It sounds like you could use some help using jQuery, I suggest StackOverflow or forum.jquery.com for that.
