### ISSUE TITLE
Merge current articles on .queue and .dequeue into a single article

### ISSUE THREAD

**Issue by ajpiano** [jquery/learn.jquery.com#77]
We don't need there to be two articles on the exact same thing. Merge `effects/queue_and_dequeue_explained.md` and `effects/uses_of_queue_and_dequeue.md` into one article.  The former article seems almost to be a good intro, whereas the second serves as a later section on more advanced usage.

**Comment by arthurvr** [comment]
I think we can just remove `queue-and-dequeue-explained.md` and keep `uses-of-queue-and-dequeue.md`. Nothing is covered in that first one that isn't in the other. In fact `queue-and-dequeue-explained.md` is just one big example, it doesn't explain that much.

Also, https://github.com/jquery/learn.jquery.com/issues/179 in fact still isn't fixed.

I'm interested in hearing your thoughts on this too, @gnarf.

Assigning this to me as I'll take it.

**Comment by arthurvr** [comment]
PR #633

**Comment by icode-git** [comment]
Hello sir, I want to fix this issue.Shall i go ahead with it?

**Comment by arthurvr** [comment]
@icode-git Any help is appreciated, but I already have an open PR (#633). There are other open tickets you can work on :)
