### ISSUE TITLE
"headings is now a jQuery element containing"

### ISSUE THREAD

**Issue by kyberkiller** [jquery/learn.jquery.com#783]
what is jQuery element? I know dom element, html element, jquery object, but the text says jquery element. confusing.

**Comment by Krinkle** [comment]
Fixed in https://github.com/jquery/learn.jquery.com/commit/53786e8731b90652a30eae3c21727aeb210e84f8. Also reported more recently in https://github.com/jquery/learn.jquery.com/issues/777.
