### ISSUE TITLE
Typo error in p tag inside div id "for-users" 

### ISSUE THREAD

**Issue by mind-ashish** [jquery/learn.jquery.com#785]
In **learn.jquery.com**, there is a typo error('than' instead of 'that') in div **id="for-users"** , text inside the p tag goes like :
"There's a lot more to learn about building web sites and applications with jQuery **than** can fit in API documentation. If you're looking for explanations of the basics, workarounds for common problems, best practices, and how-tos, you're in the right place!"

But It should be : 
"There's a lot more to learn about building web sites and applications with jQuery **that** can fit in API documentation. If you're looking for explanations of the basics, workarounds for common problems, best practices, and how-tos, you're in the right place!"

**Comment by Krinkle** [comment]
The current sentence  is "There is more to learn […] than can fit in the API documentation" is grammatically correct. "than" in this context refer sto "more", forming the "more than" comparison. I suspect you may have read it differently. It is not describing that everything to learn fits in the API documentation. If that were true, the Learning site did not need to exist :) I hope that makes sense.
