### ISSUE TITLE
information request about ECCN codes

### ISSUE THREAD

**Issue by Baldizzone** [jquery/learn.jquery.com#801]
We use the components listed below in our commercial product and therefore we need to know the ECCN for them:

bgiframe   3.0.0
jquery-migrate   - jquery/jquery-migrate 3.0.1
jQuery-SliderAccess   0.3
jQuery-Timepicker-Addon   1.4

can you help me?

Thanks a lot

**Comment by dmethvin** [comment]
All of these repos are managed by the same few people, and none of them know the answer. Please don't open any more tickets.
