### ISSUE TITLE
Some information is not rendering correctly on the Safari browser

### ISSUE THREAD

**Issue by AlfG71** [jquery/learn.jquery.com#813]
On this [page](https://learn.jquery.com/about-jquery/how-jquery-works/) of the documentation, there is a comment that begins with `**Note` in a yellow box that stops rendering at the first backtick that mentions the <script> element.

### The content displayed should be:

**Note**: When you download jQuery, the file name may contain a version number, e.g., `jquery-x.y.z.js`. Make sure to either rename this file to `jquery.js` or update the `src` attribute of the `<script>` element to match the file name.

### The actual content that appears is:

**Note**: When you download jQuery, the file name may contain a version number, e.g., `jquery-x.y.z.js`. Make sure to either rename this file to `jquery.js` or update the `src` attribute of the `

**Comment by Krinkle** [comment]
Thanks @AlfG71, I've confirmed the issue:

<img width="910" alt="Screenshot 2023-03-25 at 21 03 42" src="https://user-images.githubusercontent.com/156867/227754687-b0d844cb-2d95-4493-afa4-595683f8345c.png">

The source is at https://github.com/jquery/learn.jquery.com/blob/f2baa777409abd3343968bb7c42172439dad404c/page/about-jquery/how-jquery-works.md, which does include backticks already:

```markdown
<div class="warning">**Note**: When you download jQuery, the file
name may contain a version number, e.g., `jquery-x.y.z.js`. Make
sure to either rename this file to `jquery.js` or update the `src`
attribute of the `<script>` element to match the file name.</div>
```

 The specific markdown parser used by [grunt-jquery-content](https://github.com/jquery/grunt-jquery-content) is called [marked](https://github.com/markedjs/marked) (from @markedjs). There has been some discussion there over the years about how to support Markdown inside a `<div>` element at https://github.com/markedjs/marked/issues/488 and https://github.com/markedjs/marked/issues/985. In a nut shell, it seems adding a line break will mitigate the issue. Without it it treats the entire line as raw HTML.

**Comment by Krinkle** [comment]
Looks like that worked :)

https://stage.learn.jquery.com/about-jquery/how-jquery-works/#jquery-the-basics

<img width="881" alt="Screenshot 2023-03-25 at 21 23 00" src="https://user-images.githubusercontent.com/156867/227755215-846c8026-f380-4d4f-b19f-2036f7aaddab.png">
